### PR TITLE
Fix AWS deploy

### PR DESCRIPTION
**Pull request by matiasanaya**
### Please check if the PR fulfills these requirements

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?

Fixes some issues encountered on a fresh AWS deploy

### What is the current behavior?

It errors out.

### What is the new behavior?

YMMV

### Does this PR introduce a breaking change?

I don't think so.

### Other information:

To actually get a working AWS env you have to do a couple of extra things, so this is what I recommend:

1. Follow the [Deploy project to AWS guide](https://docs.demo.saas.apptoku.com/aws/deploy-to-aws/)
    - In [Step 3: Initialize an environment stage](https://docs.demo.saas.apptoku.com/aws/deploy-to-aws/create-env-stage-in-repo) set `SB_TOOLS_ENABLED` to `false`. I couldn't get the `tools` deployed. Sorry.
    - Skip [Step 6: Deploy the app](https://docs.demo.saas.apptoku.com/aws/deploy-to-aws/run-deployment-commands)
2. [Setup Docker Hub account](https://docs.demo.saas.apptoku.com/aws/cicd/setup-docker-hub)
3. In a brand new AWS account:
    - Concurrent builds are not allowed. You'll have to contact AWS to allow this (see [this post](https://repost.aws/questions/QUxsq-Hv5GSPa_Pth-5ZVckQ/cannot-get-codebuild-to-build-more-than-1-concurrent-build)). Alternatively you can modify the code to get all build and deploy steps to run serially. This is what I did by tweaking the `runOrder` of each step. Or you could retry failed stages
    - SES starts in sandbox mode. That means you can only send emails `from` verified addresses `to` verified addresses. See [Creating and verifying identities in Amazon SES](https://docs.aws.amazon.com/ses/latest/dg/creating-identities.html). Alternatively contact AWS to get out of the SES sandbox.
4. [Configure Automatic Deployments](https://docs.demo.saas.apptoku.com/aws/cicd/auto-deploy)
5. [Trigger CI/CD deployment manually](https://docs.demo.saas.apptoku.com/aws/cicd/trigger-cicd-manually)

Extra notes:

- [Official docs](https://docs.demo.saas.apptoku.com/aws/deploy-to-aws/configure-aws-credentials) can be outdated. If possible run and read [the local version](http://localhost:3006/aws/deploy-to-aws/configure-aws-credentials).
- Make sure to run `pnpm postinstall` after getting this code changes in place.
- Run `pnpm saas infra deploy` if you ever need to update you AWS code-pipeline
- Cloudformation can sometimes fail to create resources because names might be already in use (like S3 bucket names). Make sure your `PROJECT_NAME` + `ENV_STAGE` is rather unique. I first tried to deploy using `saas` and `dev` and that was a bad idea.
- As per #445 I set `VITE_SUBSCRIPTIONS_URL` via `pnpm saas webapp secrets` to `wss://<SB_DOMAIN_WEB_APP>/ws` which I suppose is a step in the right direction, but still couldn't get the notifications working.

### CODE REVIEW

**Comment by gabrii** [comment]
Thanks for the detailed instructions on how to actually get it to deploy. I won't be able to test it for at least a week, but I hope apptension takes a look soon!

**Comment by Crunchyman-ralph** [comment]
I was also having issues enabled `SB_Tools` the reason being that the sb_tools cloudformation isn't included in any cli commands to add it to the AWS.

**Comment by mkleszcz** [comment]
Thank you for the notes and suggestions. This feedback is very valuable for us!
As this PR contains multiple fixes and targeting multiple issues I will try to break it down into some smaller chunks that we can solve:
1. **Issue with SSM editor** is already fixed and merged (#452)
2. **Concurrent builds issue**: This one is a bit tricky. We had this issue in some projects that were starting from fresh AWS accounts but as far as I remember we were able to increase the limit by contacting with the AWS support. For sure it's a good idea to add this information to the docs. Also thinking about how to solve this so anyone could deploy this without waiting for the AWS response. Your changes doesn't look like build and deploy steps are running sequentially (the steps with `runOrder:2` are divided into two groups). This might help but for better pipeline performance after some time it would require to change it to the state it is currently on master. I think it would be nice to have an option to deploy all steps in sequence or concurrently based on some setting.
3. **Not able to deploy `tools`**: Could you send some logs or reason why you were not able to deploy tools? We have some issues to improve this part of SB but would be good to know why it's not working atm
4. **SES in sandbox mode**: This is how AWS SES works but we can add a note to the docs.

**Comment by matiasanaya** [comment]
@mkleszcz  - Don't forget the issue that even if people choose to disable the tools, the deploys will fail because CI is still trying to upload the version to a bucket that's part of the tools infra. I think you should keep the bit of code in this PR that fixes that.

**Comment by mkleszcz** [comment]
I have created the a separate tickets for the outstanding issues from this PR. Also most of the feedback is already implemented or released. I think we can close this PR and look on the #478 and #479.
**Thank you very much for the feedback! Contributions like this helps us a lot :)**

**Pull request closed without merging**
